# Generated by Django 3.2.5 on 2021-08-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('in_sinhala', 'in_english')},
        ),
    ]
