# Generated by Django 3.2.5 on 2021-08-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_word_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='in_singlish',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='recorde_count',
            field=models.IntegerField(default=0),
        ),
    ]
