# Generated by Django 4.0.2 on 2022-02-04 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('mobile_number_verified', models.BooleanField(default=False)),
                ('is_eligible_to_get_payed', models.BooleanField(default=False)),
                ('payed_proof_img_link', models.CharField(max_length=1500)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=25)),
                ('account_holder', models.CharField(max_length=50)),
                ('account_bank', models.CharField(max_length=50)),
                ('account_bank_branch', models.CharField(max_length=50)),
                ('payment_requested', models.BooleanField(default=False)),
                ('payment_request_status', models.CharField(max_length=500)),
                ('user_remarks', models.CharField(max_length=1500)),
                ('admin_remarks', models.CharField(max_length=1500)),
                ('nic', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
