# Generated by Django 4.0.2 on 2022-02-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='account_bank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='account_bank_branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='account_holder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='account_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='admin_remarks',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='nic',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='payed_proof_img_link',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='payment_request_status',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_remarks',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
