# Generated by Django 3.2.5 on 2021-08-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_alter_stream_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
